# Generated by Django 3.1.3 on 2020-11-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=264)),
                ('lastname', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=264)),
                ('birthdate', models.DateField()),
                ('phoneno', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=50)),
                ('file', models.FileField(max_length=264, upload_to='media')),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
