# Generated by Django 3.1.3 on 2020-11-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studuser',
            name='phoneno',
            field=models.CharField(max_length=20),
        ),
    ]
